version: '3'

services: 
    weather-service:
        build: .
        container_name: weather-prod
        restart: always
        ports:
            - 5000:5000
        environment: 
            - APP_NAME=weather-app
            - FLASK_ENV=production
        volumes: 
            - .:/app